# netlify.toml

[build]
  publish = "."
  functions = "functions"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/askAI"
  to = "/.netlify/functions/askAI"
  status = 200
